server:
  port: 7002

eureka:
  instance:
    # Eureka服务端的实例名称
    hostname: eureka7002.com
  client:
    # false表示不向注册中心注册自己。
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    # 默认为true，设置为false可关闭eureka的自我保护模式，保证不可用服务被及时剔除
#    enable-self-preservation: false
    # 与注册服务之间的心跳监测间隔时间为2s，默认为90s
#    eviction-interval-timer-in-ms: 2000