server:
  port: 8006

spring:
  application:
    name: consul-pay-service
  cloud:
    consul:
      host: 42.194.210.114
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.194.210.114:3306/cloud_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/cloud_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: pianosong

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.idol.beans
