server:
  port: 8002

spring:
  application:
    name: cloud-pay-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.194.210.114:3306/cloud_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/cloud_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: pianosong

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.idol.beans

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
    # 表示是否将自己注册进Eureka，默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
  instance:
    # 配置主机名
    instance-id: pay8002
    # 访问路径是否显示IP地址,默认为false
    prefer-ip-address: true